{{- if and (.Values.hosts) (.Values.ingress.enabled)  -}}
{{- $svcPort := .Values.containerPort -}}
{{- $fullName := include "default.fullname" . -}}
{{- $svcName := .Values.serviceName  -}}
{{- $hostUrlPath := .Values.urlpath  -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  labels:
    {{- include "default.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  tls: []
  rules:
  {{- range .Values.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - path: {{ $hostUrlPath }}/?(.*)
            backend:
              serviceName: {{ if $svcName }}{{ $svcName }}{{ else }}{{ $fullName }}-svc{{- end}}
              servicePort: {{ $svcPort }}
  {{- end }}
{{- end }}
