apiVersion: v1
kind: Service
metadata:
  name: {{ if .Values.serviceName }}{{ .Values.serviceName }}{{ else }}{{ include "default.fullname" . }}-svc{{- end}}
  labels:
    {{- include "default.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.containerPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "default.selectorLabels" . | nindent 4 }}
