apiVersion: v1
kind: Service
metadata:
  name: test-k8s-service
spec:
  selector:
    app: test-k8s
  type: NodePort
  ports:
    - port: 80        # 本 Service 的端口
      targetPort: 80  # 容器端口
      nodePort: 30000
      protocol: TCP