apiVersion: apps/v1
kind: Deployment
metadata:
  name: dots-api-quality-bi
  namespace: dots
  selfLink: /apis/apps/v1/namespaces/dots/deployments/dots-api-quality-bi
  labels:
    app.kubernetes.io/instance: dots-api-quality-bi
    app.kubernetes.io/name: dots-api
    helm.sh/chart: dots-api-0.1.0
  annotations:
    deployment.kubernetes.io/revision: '79'
    meta.helm.sh/release-namespace: dots
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: dots-api-quality-bi
      app.kubernetes.io/name: dots-api
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: dots-api-quality-bi
        app.kubernetes.io/name: dots-api
      annotations:
        checksum/configmap: 78c1410218af98f090a061495ea9d52e53cafbb1c00acae509589105e265143c
        checksum/secret: b31da1ac8c6427aeddc1bef83b9023527e701f7f3c33341938ccad819b31cc6c
        kubectl.kubernetes.io/restartedAt: '2021-12-30T05:15:44Z'
    spec:
      containers:
        - name: quality-bi
          image: >-
            china-dots-system-docker-local.arf.tesla.cn/dots/api-eng/quality:e80faf9ac8c949119b771e3e4289a33f6b5534bc
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: dots-api-quality-bi
            - secretRef:
                name: dots-api-quality-bi
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 160m
              memory: 160Mi
          livenessProbe:
            httpGet:
              path: /api/quality-bi/healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/quality-bi/ping
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext: {}
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: regcred
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
